Repository AlmaLinux/wiki, pull requests merged in 2024-05, with the labels that each got.

#402 Updates to the Cloud SIG page
  docs/sigs/Cloud.md
Labels: documentation, enhancement, needs-review

#406 adding May minutes and June agenda links
  docs/Transparency.md
Labels: needs-review

#399 Add secure boot key generation and handling guide
  docs/.vuepress/config.js
  docs/development/secure-boot.md
Labels: documentation, enhancement

#404 New addition to the HowTo series explaining how to deploy a LAMP server.
  docs/.vuepress/config.js
  docs/.vuepress/public/images/HowTo-LAMP-server-1.png
  docs/.vuepress/public/images/HowTo-LAMP-server-2.png
  docs/series/LAMP-server.md
Labels: needs-review

#419 8.10 release
  docs/.vuepress/config.js
  docs/release-notes/8.10.md
  docs/release-notes/README.md
Labels: documentation

#425 Adding the funding request form
  docs/sigs/README.md
Labels: documentation

#310 Added new links to HowTo.md
  docs/Howto.md
Labels: documentation
