Repository AlmaLinux/wiki, pull requests merged in 2024-09, with the labels that each got.

#484 Updates to ELevate Contribution information across the wiki
  docs/.vuepress/public/images/elevate-testing-scheme.svg
  docs/Contribute-to-Testing.md
  docs/elevate/Contribution-guide.md
  docs/elevate/ELevate-NG-testing-guide.md
  docs/elevate/ELevate-quickstart-guide.md
  docs/elevate/ELevate-testing-guide.md
  docs/elevate/ELevating-CentOS7-to-AlmaLinux-9.md
  docs/elevate/README.md
  docs/migration/README.md
  docs/sigs/Migration.md
Labels: documentation, enhancement

#254 Rename Building Packages for AlmaLinux to AlmaLinux Package Building …
  docs/.vuepress/config.js
  docs/documentation/package-building-guide.md
Labels: enhancement

#492 Failed to commit this image to a previous PR.
  docs/.vuepress/public/images/2023.updated.almafedoraRedhatoverview.png
Labels: bug

#497 Clarifying life of minor versions
  docs/FAQ.md
  docs/release-notes/README.md
Labels: enhancement

#496 Added more information to reflect the fact that the SIG is launched
  docs/sigs/Certification.md
Labels: enhancement

#498 Updated SBOM guide
  docs/.vuepress/public/images/sbom-details.png
  docs/.vuepress/public/images/sbom-details2.png
  docs/documentation/sbom-guide.md
Labels: documentation, enhancement

#500 Added ELevate Changelog
  docs/.vuepress/config.js
  docs/elevate/Changelog.md
Labels: documentation
