Repository AlmaLinux/wiki, pull requests merged in 2024-04, with the labels that each got.

#381 New Weblate documentation
  docs/.vuepress/public/images/weblate-almalinux-foundation.png
  docs/.vuepress/public/images/weblate-ask-new-lang.png
  docs/.vuepress/public/images/weblate-create-account.png
  docs/.vuepress/public/images/weblate-send-translations.png
  docs/.vuepress/public/images/weblate-translate-website.png
  docs/Help-translating-site.md
Labels: enhancement

#385 Added ELevating CentOS 6 to CentOS 7 guide
  docs/.vuepress/config.js
  docs/elevate/ELevating-CentOS6-to-CentOS7.md
Labels: enhancement

#390 Adding Help-translating-site
  docs/.vuepress/config.js
  docs/sigs/Marketing.md
Labels: bug

#384 adding a list of ideas for how to contribute
  docs/Contribute.md
Labels: documentation

#380 Added links to github packages/reorganized tables
  docs/containers/docker-images.md
Labels: enhancement
