Repository AlmaLinux/wiki, pull requests merged in 2024-07, with the labels that each got.

#422 Adding a little bit about why we use cats in our codenames.
  docs/FAQ.md
  docs/release-notes/README.md
Labels: documentation, enhancement

#273 Adding kickstart guide
  docs/Howto.md
  docs/documentation/kickstart-guide.md
Labels: enhancement

#455 add .run driver installation to NVIDIA: Installation on 9.x Update SystemSeriesA03R9.md
  docs/series/system/SystemSeriesA03R9.md
Labels: enhancement

#458 Earlyoom (Out of Memory) Installation Guide - Create SystemSeriesA08.md
  docs/series/system/SystemSeriesA08.md
Labels: enhancement, question

#444 Not enough space in overlay file on XFS filesystem
  docs/elevate/ELevate-frequent-issues.md
Labels: enhancement, question
